#9 Sprint 9
aleshchenko37/java-filmorate pull request #1
Opened 2023-07-20 06:49 UTC by aleshchenko37

2023-07-20 08:38 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Data
Правильно что используешь @Data

2023-07-20 08:39 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/validators/FilmValidator.java
> +public class FilmValidator {
Хорошо что вынесла валидацию в отдельный класс.

2023-07-20 08:44 UTC, VadimZharkov requested changes
Все хорошо. Что можно улучшить.
Т.к. у контроллеров есть общее поведение в части работы с мапами и идентификаторами, то можно сделать базовый контроллер и в него вынести общую часть.
Далее Фильм и Юзер имеют общую функциональность связанную с id. Можно сделать базовый класс или интерфейс, назвать например Entity и в него вынести то что связано с id.

2023-07-20 14:56 UTC, aleshchenko37 commented
Внесены правки

2023-07-21 05:49 UTC, VadimZharkov approved these changes

2023-07-21 06:44 UTC, merged